let suggestions =[
    "Don't give girls compliment all the time",
    "Work on self-improvement",
    "Don’t do too many favors too often.",
    "Don’t always drop everything for them.",
    "Communicate your boundaries.",
    " Don’t neglect your friends and family.",
    " Don’t try too hard.",
    "Don’t overdo it with chivalry",
    " Get to know a woman on a deeper level",
    "Be okay with being single.",
    "fool",
    "lunatic",
    "goose",
    "idiot",
    "simpleton",
    "ninny",
    "jackass",
    "doofus",
    "loser",
    "git",
    "charlie",
    "booby",
    "berk",
    "turkey",
    "cuckoo",
    "monkey",
    "featherhead",
    "charley",
    "How to avoid being a simp",
    "Who is a simp",
    "How to become real in life",
    "How to avoid being a nice guy"
]